/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Controladores.ControladorGeneral;
import Controladores.ControladorPanelCorrelativas;
import ModeloLogico.Carrera;
import ModeloLogico.Facultad;
import ModeloLogico.Materia;
import javax.swing.JOptionPane;

/**
 *
 * @author juans
 */
public class PanelCorrelativas extends javax.swing.JPanel {

    /**
     * Creates new form PanelCorrelatibas
     */
    public PanelCorrelativas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        panelSeleccion = new javax.swing.JPanel();
        jlCarrera = new javax.swing.JLabel();
        cbCarreras = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMaterias = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        panelAsingnacion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMaterias = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCorrelativas = new javax.swing.JList<>();
        jlMaterias = new javax.swing.JLabel();
        jlCorrelativa = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        botonQuitar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 204, 255));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        panelSeleccion.setBackground(new java.awt.Color(72, 84, 84));

        jlCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelCorrelativas/jlCarreras.png"))); // NOI18N

        cbCarreras.setSelectedItem(null);
        cbCarreras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCarrerasItemStateChanged(evt);
            }
        });
        cbCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCarrerasActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelCorrelativas/jlTexto.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelCorrelativas/jlMaterias.png"))); // NOI18N

        cbMaterias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMateriasItemStateChanged(evt);
            }
        });
        cbMaterias.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbMateriasPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout panelSeleccionLayout = new javax.swing.GroupLayout(panelSeleccion);
        panelSeleccion.setLayout(panelSeleccionLayout);
        panelSeleccionLayout.setHorizontalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jlCarrera))
                        .addGap(31, 31, 31)
                        .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSeleccionLayout.setVerticalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCarreras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28))
        );

        panelAsingnacion.setBackground(new java.awt.Color(72, 84, 84));

        jScrollPane1.setViewportView(listaMaterias);

        jScrollPane2.setViewportView(listaCorrelativas);

        jlMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelCorrelativas/jlMaterias2.png"))); // NOI18N

        jlCorrelativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelCorrelativas/jlCorrelativas.png"))); // NOI18N

        botonAgregar.setBackground(new java.awt.Color(72, 84, 84));
        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelCorrelativas/bFlechaAzul.png"))); // NOI18N
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonQuitar.setBackground(new java.awt.Color(72, 84, 84));
        botonQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelCorrelativas/bFlechaRoja.png"))); // NOI18N
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAsingnacionLayout = new javax.swing.GroupLayout(panelAsingnacion);
        panelAsingnacion.setLayout(panelAsingnacionLayout);
        panelAsingnacionLayout.setHorizontalGroup(
            panelAsingnacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsingnacionLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(panelAsingnacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAsingnacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlCorrelativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addGap(109, 109, 109))
            .addGroup(panelAsingnacionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAsingnacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregar)
                    .addComponent(botonQuitar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelAsingnacionLayout.setVerticalGroup(
            panelAsingnacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsingnacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAsingnacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAsingnacionLayout.createSequentialGroup()
                        .addComponent(jlCorrelativa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAsingnacionLayout.createSequentialGroup()
                        .addComponent(jlMaterias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelAsingnacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAsingnacionLayout.createSequentialGroup()
                        .addComponent(botonAgregar)
                        .addGap(144, 144, 144)
                        .addComponent(botonQuitar))
                    .addGroup(panelAsingnacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(panelSeleccion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(panelAsingnacion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAsingnacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAsingnacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCarrerasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCarrerasItemStateChanged
        
        //Identifico si la carrera tiene materias}
        
        String nomcarrera = (String) PanelCorrelativas.cbCarreras.getSelectedItem();
        int indice1 = ControladorGeneral.buscarCarrera(nomcarrera);  // SIMPLIFICAR LA BUSQUEDA 
        Carrera c1 = Facultad.carrerasFacultad.get(indice1);
        
        if (!c1.listamaterias.isEmpty()){
            ControladorPanelCorrelativas.actualizarcomboMaterias();
            ControladorPanelCorrelativas.actualizarlistaCorrelativas();}
        else{
            
            cbMaterias.removeAllItems();
            listaMaterias.removeAll();
            
            JOptionPane.showMessageDialog(null,"LA CARRERA NO POSEE MATERIAS ASIGNADAS");}
 
    }//GEN-LAST:event_cbCarrerasItemStateChanged

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        ControladorPanelCorrelativas.agregarCorrelativa();// TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        ControladorPanelCorrelativas.quitarCorrelativa();// TODO add your handling code here:
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void cbMateriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMateriasItemStateChanged
        ControladorPanelCorrelativas.actualizarlistaMaterias();
    }//GEN-LAST:event_cbMateriasItemStateChanged

    private void cbMateriasPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbMateriasPopupMenuWillBecomeInvisible
        ControladorPanelCorrelativas.actualizarlistaCorrelativas();
    }//GEN-LAST:event_cbMateriasPopupMenuWillBecomeInvisible

    private void cbCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCarrerasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonQuitar;
    public static javax.swing.JComboBox<String> cbCarreras;
    public static javax.swing.JComboBox<String> cbMaterias;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlCarrera;
    private javax.swing.JLabel jlCorrelativa;
    private javax.swing.JLabel jlMaterias;
    public static javax.swing.JList<String> listaCorrelativas;
    public static javax.swing.JList<String> listaMaterias;
    private javax.swing.JPanel panelAsingnacion;
    private javax.swing.JPanel panelSeleccion;
    // End of variables declaration//GEN-END:variables
}
