/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Controladores.ControladorPanelMaterias;

/**
 *
 * @author juans
 */
public class VentanaEdicionMaterias extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEdicionMaterias
     */
    public VentanaEdicionMaterias() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlnombre = new javax.swing.JLabel();
        botonGuardarYSalir = new javax.swing.JButton();
        jlcuatrimestre = new javax.swing.JLabel();
        jlaño = new javax.swing.JLabel();
        jlPromo = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jtNewNombre = new javax.swing.JTextField();
        jtNewAño = new javax.swing.JTextField();
        jlEdiciondeAlumno = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jcbNewpromocion = new javax.swing.JComboBox();
        jcbNewtipo = new javax.swing.JComboBox<>();
        jtNewCuatrimestre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(72, 84, 84));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jlnombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelMaterias/jlNombre.png"))); // NOI18N

        botonGuardarYSalir.setBackground(new java.awt.Color(72, 84, 84));
        botonGuardarYSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelMaterias/botonGuardarySalir(edicion).png"))); // NOI18N
        botonGuardarYSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarYSalirActionPerformed(evt);
            }
        });

        jlcuatrimestre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelMaterias/jlCuatrimestre.png"))); // NOI18N

        jlaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelMaterias/jlAño.png"))); // NOI18N

        jlPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelMaterias/jlPromo.png"))); // NOI18N

        jlTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelMaterias/jlTipo.png"))); // NOI18N
        jlTipo.setToolTipText("");

        jlEdiciondeAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PanelMaterias/jlMenudeEdicionMaterias(edicion.png"))); // NOI18N

        jcbNewpromocion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jcbNewpromocion.setSelectedItem(null);

        jcbNewtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Obligatoria", "Opcional" }));
        jcbNewtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNewtipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlnombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtNewNombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlTipo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbNewtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlaño)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtNewAño))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlPromo)
                                            .addComponent(jlcuatrimestre))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbNewpromocion, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtNewCuatrimestre)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlEdiciondeAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator1))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(botonGuardarYSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlEdiciondeAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtNewNombre))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtNewAño, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlaño)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlcuatrimestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtNewCuatrimestre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPromo)
                    .addComponent(jcbNewpromocion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlTipo)
                    .addComponent(jcbNewtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(botonGuardarYSalir)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarYSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarYSalirActionPerformed
        ControladorPanelMaterias.modificarMateria();
       
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarYSalirActionPerformed

    private void jcbNewtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNewtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNewtipoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarYSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JComboBox jcbNewpromocion;
    public static javax.swing.JComboBox<String> jcbNewtipo;
    private javax.swing.JLabel jlEdiciondeAlumno;
    private javax.swing.JLabel jlPromo;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlaño;
    private javax.swing.JLabel jlcuatrimestre;
    private javax.swing.JLabel jlnombre;
    public static javax.swing.JTextField jtNewAño;
    public static javax.swing.JTextField jtNewCuatrimestre;
    public static javax.swing.JTextField jtNewNombre;
    // End of variables declaration//GEN-END:variables
}
