package Interfaz;

import Controladores.ControladorPanelAlumnos;
import Controladores.ControladorPanelCarrera;
import Controladores.ControladorPanelCorrelativas;
import Controladores.ControladorPanelGestorNotas;
import Controladores.ControladorPanelHistoriaA;
import Controladores.ControladorPanelInscripciones;
import Controladores.ControladorPanelMaterias;
import java.awt.BorderLayout;
import javax.swing.JPanel;

public class VentanaP extends javax.swing.JFrame {

    public VentanaP() {
        initComponents(); 
       
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        botonAlumno = new javax.swing.JButton();
        botonCarrera = new javax.swing.JButton();
        botonMaterias = new javax.swing.JButton();
        botonInscripciones = new javax.swing.JButton();
        botonGestorNotas = new javax.swing.JButton();
        botonHistoriaA = new javax.swing.JButton();
        botonCorrelativas = new javax.swing.JButton();
        PanelContenedor = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 665));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 665));

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1020, 640));

        PanelBotones.setBackground(new java.awt.Color(72, 84, 84));
        PanelBotones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelBotones.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/VentanaPrincipal/jlLogoPanel.png"))); // NOI18N

        botonAlumno.setBackground(new java.awt.Color(72, 84, 84));
        botonAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/VentanaPrincipal/balumnos.png"))); // NOI18N
        botonAlumno.setToolTipText("");
        botonAlumno.setMaximumSize(new java.awt.Dimension(195, 39));
        botonAlumno.setMinimumSize(new java.awt.Dimension(195, 39));
        botonAlumno.setOpaque(true);
        botonAlumno.setPreferredSize(new java.awt.Dimension(195, 39));
        botonAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlumnoActionPerformed(evt);
            }
        });

        botonCarrera.setBackground(new java.awt.Color(72, 84, 84));
        botonCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/VentanaPrincipal/bcarreras.png"))); // NOI18N
        botonCarrera.setMaximumSize(new java.awt.Dimension(195, 39));
        botonCarrera.setMinimumSize(new java.awt.Dimension(195, 39));
        botonCarrera.setOpaque(true);
        botonCarrera.setPreferredSize(new java.awt.Dimension(195, 39));
        botonCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarreraActionPerformed(evt);
            }
        });

        botonMaterias.setBackground(new java.awt.Color(72, 84, 84));
        botonMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/VentanaPrincipal/bmaterias.png"))); // NOI18N
        botonMaterias.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        botonMaterias.setPreferredSize(new java.awt.Dimension(195, 39));
        botonMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMateriasActionPerformed(evt);
            }
        });

        botonInscripciones.setBackground(new java.awt.Color(72, 84, 84));
        botonInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/VentanaPrincipal/binscripciones.png"))); // NOI18N
        botonInscripciones.setPreferredSize(new java.awt.Dimension(195, 39));
        botonInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInscripcionesActionPerformed(evt);
            }
        });

        botonGestorNotas.setBackground(new java.awt.Color(72, 84, 84));
        botonGestorNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/VentanaPrincipal/bgestornotas.png"))); // NOI18N
        botonGestorNotas.setPreferredSize(new java.awt.Dimension(195, 39));
        botonGestorNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestorNotasActionPerformed(evt);
            }
        });

        botonHistoriaA.setBackground(new java.awt.Color(72, 84, 84));
        botonHistoriaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/VentanaPrincipal/bhistorial.png"))); // NOI18N
        botonHistoriaA.setOpaque(true);
        botonHistoriaA.setPreferredSize(new java.awt.Dimension(195, 39));
        botonHistoriaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHistoriaAActionPerformed(evt);
            }
        });

        botonCorrelativas.setBackground(new java.awt.Color(72, 84, 84));
        botonCorrelativas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/VentanaPrincipal/botonCorrelativas.png"))); // NOI18N
        botonCorrelativas.setPreferredSize(new java.awt.Dimension(195, 39));
        botonCorrelativas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCorrelativasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jlLogo))
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(botonAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(botonCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(botonMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(botonCorrelativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(botonInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(botonGestorNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(botonHistoriaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlLogo)
                .addGap(39, 39, 39)
                .addComponent(botonAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(botonCorrelativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(botonInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(botonGestorNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(botonHistoriaA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelContenedor.setBackground(new java.awt.Color(204, 204, 255));
        PanelContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelContenedor.setAlignmentX(0.0F);
        PanelContenedor.setLayout(new java.awt.BorderLayout());

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/VentanaPrincipal/jlLogo.png"))); // NOI18N
        Logo.setLabelFor(Logo);
        Logo.setAlignmentX(0.5F);
        PanelContenedor.add(Logo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void agregarPanel(JPanel panel){
       
        panel.setSize(800, 600);
        panel.setLocation(0,0);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(panel, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
   
   }

 
    
    private void botonAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlumnoActionPerformed

        PanelAlumnos panel = new PanelAlumnos();
        agregarPanel(panel);
        ControladorPanelAlumnos.actualizarTabla();
        
    }//GEN-LAST:event_botonAlumnoActionPerformed

    private void botonCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarreraActionPerformed
       
        PanelCarreras panel = new PanelCarreras();
        agregarPanel(panel);
        ControladorPanelCarrera.actualizarTabla();
    }//GEN-LAST:event_botonCarreraActionPerformed

    private void botonMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMateriasActionPerformed
         
        PanelMaterias panel = new PanelMaterias();
        agregarPanel(panel);
        
        ControladorPanelMaterias.actualizarCombodeCarreras(PanelMaterias.listacarreras);
        
    }//GEN-LAST:event_botonMateriasActionPerformed

    private void botonHistoriaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHistoriaAActionPerformed
        PanelHistorialA panel = new PanelHistorialA();
        agregarPanel(panel);
        
        ControladorPanelHistoriaA.actualizarAlumnos();
        
    }//GEN-LAST:event_botonHistoriaAActionPerformed

    private void botonInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInscripcionesActionPerformed
        PanelInscripciones panel = new PanelInscripciones();
        agregarPanel(panel);
        
        
        ControladorPanelInscripciones controlador = new ControladorPanelInscripciones();
        
        
        controlador.actualizarcomboAlumnos(PanelInscripciones.listaalumnos); 
        controlador.actualizarcomboCarreras(PanelInscripciones.listacarreras);
        controlador.identificarAlumno();   
        
    }//GEN-LAST:event_botonInscripcionesActionPerformed

    private void botonGestorNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestorNotasActionPerformed
         PanelGestorNotas panel = new PanelGestorNotas();
         agregarPanel(panel);
         
         ControladorPanelGestorNotas.actualizarcomboAlumnos(PanelGestorNotas.listaalumnos);
    }//GEN-LAST:event_botonGestorNotasActionPerformed

    private void botonCorrelativasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCorrelativasActionPerformed
        PanelCorrelativas panel = new PanelCorrelativas();
        agregarPanel(panel);
        
        ControladorPanelCorrelativas.actualizarcomboCarreras(PanelCorrelativas.cbCarreras);
    }//GEN-LAST:event_botonCorrelativasActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelBotones;
    public static javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton botonAlumno;
    private javax.swing.JButton botonCarrera;
    private javax.swing.JButton botonCorrelativas;
    private javax.swing.JButton botonGestorNotas;
    private javax.swing.JButton botonHistoriaA;
    private javax.swing.JButton botonInscripciones;
    private javax.swing.JButton botonMaterias;
    private javax.swing.JLabel jlLogo;
    // End of variables declaration//GEN-END:variables
}
